version: "3"
services:
  hotdrop_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /home/node/app
    command: ash -c "npm install && ts-node index.ts"
    ports:
      - "3241:3241"
  hotdrop_coturn:
    image: instrumentisto/coturn
    restart: on-failure
    command:
      - -c=/etc/coturn/turnserver.conf
      - --external-ip=$$(detect-external-ip)
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    network_mode: host
  hotdrop_nginx:
    build:
      context: .
      dockerfile: ClientDockerfile
    depends_on:
      - hotdrop_server
      - hotdrop_coturn
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
