version: "3"
services:
  hotdrop_server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    command: ash -c "npm install && ts-node index.ts"
    ports:
    - 3000:3000
  hotdrop_nginx:
    build:
      context: .
      dockerfile: ClientDockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
