version: "3"
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3241:3241"
  coturn:
    image: instrumentisto/coturn
    restart: on-failure
    command:
      - -c=/etc/coturn/turnserver.conf
      - --external-ip=$$(detect-external-ip)
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    network_mode: host
  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
      - coturn
    ports:
      - "8080:80"
